services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/templates_dev:/etc/nginx/templates
      - ./service-frontend/dist:/usr/share/nginx/service-frontend/dist
      - ./web_service/media:/usr/src/app/media
      - ./web_service/static:/usr/src/app/static
    depends_on:
      - backend
    env_file:
      - .env.dev

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./web_service:/service/web_service

    command: ../entrypoint.dev.sh
    environment:
      DJANGO_DATABASE_HOST: database
      DJANGO_REDIS_HOST: redis
    env_file:
      - .env.dev

    depends_on:
      - database
      - redis

  database:
    image: postgres:14.6-alpine
    ports:
      - 3305:5432
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
      - ./pg_dump:/service/pg_dump
    env_file:
      - .env.dev

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A config worker --loglevel=info
    volumes:
      - ./web_service:/service/web_service
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - .env.dev

volumes:
  dev_postgres_data: