# Generated by Django 4.2.1 on 2023-05-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('third_name', models.CharField(max_length=50, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('number', models.CharField(blank=True, max_length=9, verbose_name='Госномер')),
                ('sts', models.CharField(blank=True, max_length=10, verbose_name='Номер свидетельства о регистрации')),
                ('sold_date', models.DateField(blank=True)),
                ('engine_vol', models.CharField(max_length=3, verbose_name='Объём двигателя')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=150, verbose_name='Операция')),
                ('working_time', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Количество нормо-часов')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part', models.CharField(max_length=150, verbose_name='Запчасть')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_type', models.CharField(max_length=50, verbose_name='Тип нормочаса')),
                ('price', models.PositiveIntegerField(max_length=4, verbose_name='Стоимость нормочаса')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.acceptor')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.avto')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.maintenance')),
            ],
        ),
        migrations.AddField(
            model_name='maintenance',
            name='warehouses',
            field=models.ManyToManyField(to='service.warehouse'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='working_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.workingprice'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('image', models.CharField(max_length=100)),
                ('coef', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Коэффициент')),
                ('warehouses', models.ManyToManyField(to='service.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='avto',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.carmodel'),
        ),
    ]
