# Generated by Django 4.2.1 on 2023-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingprice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Стоимость нормочаса'),
        ),
    ]
