# Generated by Django 3.2.16 on 2023-11-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='service.engine'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='engine',
            name='oil',
        ),
        migrations.AddField(
            model_name='engine',
            name='oil',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='service.oil'),
            preserve_default=False,
        ),
    ]
