# Generated by Django 3.2.16 on 2023-12-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20231202_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Предварительная стоимость'),
        ),
    ]
