# Generated by Django 3.2.16 on 2023-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20231209_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='operation',
            field=models.CharField(max_length=150, verbose_name='Операция'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.UniqueConstraint(fields=('operation', 'car_model'), name='maintenance'),
        ),
    ]
