# Generated by Django 3.2.16 on 2023-12-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_sts_avto_vehicle_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine',
        ),
        migrations.AddField(
            model_name='avto',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avtos', to='service.engine', verbose_name='Двигатель'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='compatible_engines',
            field=models.ManyToManyField(related_name='carmodels', to='service.Engine', verbose_name='Двигатель'),
        ),
    ]
