# Generated by Django 3.2.16 on 2023-12-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20231214_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='service.engine', verbose_name='Двигатель'),
        ),
    ]
