# Generated by Django 3.2.16 on 2023-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_maintenance_engine'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenance',
            name='maintenance',
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.UniqueConstraint(fields=('operation', 'car_model', 'engine'), name='maintenance'),
        ),
    ]
