# Generated by Django 3.2.16 on 2024-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20231223_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptor',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='acceptor',
            old_name='patronim',
            new_name='patronymic',
        ),
    ]
