# Generated by Django 3.2.16 on 2024-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20240123_2057'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('day', 'time', 'acceptor'), name='unique_registration'),
        ),
    ]
