# Generated by Django 3.2.16 on 2024-01-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bot_user_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='id пользователя телеграм'),
        ),
    ]
