# Generated by Django 3.2.16 on 2024-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_bot_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patronim',
            new_name='patronymic',
        ),
    ]
